browser.css
sidebar.css

This stops them from drawing over the search suggestions.
I played around with trying to center the search suggestions as well for a more streamlined experience, but didn't have much luck. Might try that later.
Love the theme, by the way.

updated z-index for section labels

---

navbar.css
urlbar.css

I am not sure exactly how I want this, but this is more of a quick fix to avoid issues with the "navabar" text appearing over elements.

fix: contain all navbar elements inside border

---

flake.lock
flake.nix
nix/default.nix
nix/hm-module.nix
readme.md

Hello, thanks for this awesome theme!
I created a home-manager module for Nix/NixOS users.
I threw this together pretty quickly, so its probably missing some stuff that would be nice, but in terms of just installing the theme it seems to be working
For Nix users, all you have to do is add the repo as a flake input, import the module into home-manager and enable the following settings
```
textfox = {
enable = true;
profile = "firefox profile name here"
};
``` 
I couldn't find a way to get the default firefox profile, which is why you have to specify it yourself.
It's also probably possible to install the Sidebery config, but I haven't tried this yet
I haven't updated the README yet with the proper instructions as its getting quite late for me, but I plan to do this so I'll mark this PR as …

feat: add Nix support via home-manager module

---

chrome/navbar.css

by default, continues to hide the identity box, but allow it to popup on insecure websites (to show if a site is insecure) and websites asking for permissions (rather than it weirdly flickering in and out).
to recreate the original problem:
1. go to a site that will require mic/camera permissions (i went to google meet and setup an instant meeting)
2. when the site asks you to enable your mic/camera, the permission box will flicker in and out at the top left of the window
_PS: thanks for publishing the css @adriankarlen, it looks great_

fix identity box flickering in and out when asking for permissions on sites

---

chrome/browser.css

Fixed broken margins for Firefox v132.0

fix: mark #tabbrowser-tabbox margins and paddings to !important

---

nix/hm-module.nix
readme.md

This is currently more an RFC @adriankarlen and maybe @shadeyg56 .
Since [custom configuration](https://github.com/adriankarlen/textfox/pull/53) is possible, it's easy to adapt the nix home-manager module.
With this PR, it would be possible to configure font family, font size and horizontal tabs, using nix.
**Advantages:**
- Allowing a (nix-)idiomatic usage of textfox
- Much more convenient for home manager users
**Potential challenge:**
- Changes in defaults always have to be taken into account for `hm-module.nix` to preserve the documented behaviour
If you would be willing to merge such a feature @adriankarlen , I can finalize the missing options.
I just don't yet understand all  config options, e.g. `--tf-accent`. I think it would be a good idea to explain these in the README's custom …

feat: expose some configuration options to home manager module

---

chrome/content/sidebery.css

i found your project today and i think it's a really nice design, however i noticed that when i enabled "Show titles of pinned tabs" in sidebery's settings that the tab widths were no longer correct. i thought i'd put this here in case you wanted to upstream it

adjusted sidebery.css for pinned tab titles

---

chrome/defaults.css
chrome/tabs.css
readme.md

Hello, thanks for making this amazing css! 
I've added the tui border around Firefox's native vertical tabs, as mentioned by (#22). I tested it along with the horizontal tabs, and both seem to work fine. However, I did not test with sidebery. 
Also added a config for the "Sidebar customization" button that appears on the sidebar. While doing this I corrected the comment on `--tf-display-nav-buttons`  as its visibility uses `flex` rather than `block`.

feat: support for native vertical tabs

---

chrome/defaults.css
chrome/navbar.css
chrome/overwrites.css
chrome/sidebar.css
chrome/tabs.css
nix/hm-module.nix
readme.md

This PR extends upon #79 by adding a box for the tools and extensions and updating the box title for when the tools is opened to "tool" instead of "tabs" (since this was previously used by sidebery.
Added some other minor fixes to the titlebar and navbar that popped up when enabling the flag.
Resolves #22 
Preview:

fix: style entire sidebar revamp

---

chrome/defaults.css
chrome/tabs.css
nix/hm-module.nix
readme.md

This change is **only** compatible with native vertical tabs and/or horizontal tabs being shown.

feat: add option to display/hide window controls

---

nix/hm-module.nix

Hi, this fixes a single character error in hm-module.nix that was keeping my config from building
changed `lib.mkoption` to `lib.mkOption`

Nix: fix broken attribute in hm-module

---

flake.nix
nix/hm-module.nix

This PR
* Adds "aarch64-darwin" as an output system
* Sets the profiles directory based on host platform, so that chroma files are correctly placed in `~/Library/Application Support/Firefox/Profiles/<profile>/chroma` on Mac OS.
Running this locally now on Mac OS without issues. Though you might be interested in merging if it doesn't break anything on your end, seeing that it's such an unintrusive change that enables mac users to install textfox via home manager. :)

Support aarch64-darwin as a target

---

nix/hm-module.nix

As the title says the home manager should be fixed with this PR regarding border radius.
~~BUT: border is still not working for me regardless. I will try to figure out why but guess this could be merged regardless if I didn't misunderstand something?~~

fix: correct css generation for border radius in hm module

---

nix/hm-module.nix

Might be better to import firefox's config using a @import instead, but this just appends the firefox config onto the end of the userChrome.css
fixes #106

fix: home-manager module rewriting firefox's userChrome setting

---

chrome/navbar.css

For some reason unbeknownst to man the bookmarking menu uses the #identity-icon id.
When this icon is hidden, the bookmarking popup is also hidden, this resolves this issue by removing the icon image instead.
Actually resolves #77

fix(navbar): remove list-style-image instead of hiding icon

---

chrome/defaults.css
chrome/navbar.css
readme.md

As discussed in https://github.com/adriankarlen/textfox/discussions/109, this PR makes the margin and padding configurable. This makes it easy for people to adjust the size of the toolbar to their desktop environment.

feat(navbar): configurable navbar margin and padding

---

nix/modules/home-manager.nix

When rebuilding my system, I would get this evaluation warning:
Adding `.packages` at the end of the `extensions` declaration seemed to fix the issue.

Fixed evaluation warning by adding packages to firefox.extensions

---

nix/modules/home-manager.nix

Commit c49cd64 for PR #123  by @Antisune101 breaks home-manager uasge for me:
```
error: A definition for option `programs.firefox.profiles.convenient.extensions' is not of type `list of package'. Definition values:
- In `/nix/store/ly02k47f5y4h98gn86xwzwbxizpa25yd-source/collections/_/firefox.nix':
{
packages = [
<derivation sidebery-5.2.0>
];
}
```
Before merging this PR it would probably good to know where problems come from.
I am using  the latest stable home-manager and nixpkgs version `24.11`.
@Antisune101 Since I am guessing that our home-manager versions differ, can you share what you are using?
In case this is really the underlying problem, @adriankarlen it might be nexcessary to think about which home-manager version should be supported.

revert: fix extension declaration

---

nix/modules/home-manager.nix

This should hopefully be a more permanent fix to #123 breaking home-manager config on some versions. 
I've declared a `useLegacyExtensions` option that when enabled configures extensions with just `extensions` instead of `extensions.packages`. Users using a version of home manager newer than  nix-community/home-manager#6389 can set this to false to get rid of the warning.
It seems to be working on my system, but I haven't been able to test it on a system using that's using home-manager `24.11`. 
@snaeil , could you perhaps test it on your system to see if everything is working?

feat: Add support for "legacy" extension configuration

---

nix/modules/options.nix

I found that it was not possible to add custom lines to the config with first completely overwriting it, so I added an `extraConfig` option.

feat(nix): add extraConfig option

---

nix/modules/options.nix

Fix nix build, missing semicolon meant the build would hit a syntax error.

fix(nix): add missing semicolon

---

flake.lock
nix/modules/home-manager.nix

Originally, I tried to just update flake's NUR version without a need to fork textfox:
```
textfox = {
url = "github:ButterSus/textfox";
inputs.nur.follows = "nur";
};
```
But NUR changed its home manager module attribute, making recent versions of NUR incompatible with textfox.

fix: update nur flake input

---

flake.lock
flake.nix
nix/modules/home-manager.nix

Closes #150
I haven't tested this with standalone home-manager.
This removes the NUR from this flake. It seems to only be used for these addons so i don't see why not just use the addon repo from Rycee directly.
@snaeil

fix: build failure with home-manager module

---

nix/modules/home-manager.nix

There's no reason to expect people to be running legacy home-manager by default.

fix!: default useLegacyExtensions to false
